config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users

  resources :users
  match '/profile_update',  to: 'users#update',            via: 'get'
  match '/profile_edit',  to: 'users#edit',            via: 'get'
  match '/profile',  to: 'users#show',            via: 'get'
  match '/inbox', to: 'users#list_conversations',       via: 'post' ,    defaults:{ format: 'js' }
  match '/unread', to: 'users#unread',       via: 'post' ,    defaults:{ format: 'js' }
  match '/delete', to: 'users#delete_dialog',       via: 'post' ,    defaults:{ format: 'js' }
  match '/delete_selected', to: 'conversations#destroy',       via: 'post' ,    defaults:{ format: 'js' }
  match '/favarite', to: 'favorites#add',       via: 'get'
  match '/del_from_favarite', to: 'favorites#delete',       via: 'get' 
  authenticated :user do
    root 'users#index'
  end

  unauthenticated :user do
    devise_scope :user do
      get "/" => "devise/sessions#new"
    end
  end

  resources :conversations do
    resources :messages
  end

  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :lastseenable

         has_many :conversations, :foreign_key => :sender_id
         has_one :profile
         has_many :favorites
         has_many :users, :source => :favorite, :through => :favorites


    mount_uploader :picture, PictureUploader

  def self.online_now
    where("last_seen > ?", 5.minutes.ago)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate_user!

  def index
      @user = current_user  
      @users = User.where.not("id = ?",current_user.id).order("created_at DESC")
      @conversations = Conversation.involving(current_user).order("created_at DESC")
      @favorites = Favorite.where(first_id: current_user.id)
  end

  def list_conversations
    @users = User.where.not("id = ?",current_user.id).order("created_at DESC")
    @conversations = Conversation.involving(current_user).order("created_at DESC")
    respond_to do |format|
      format.js 
    end
  end

  def unread
    @users = User.where.not("id = ?",current_user.id).order("created_at DESC")
    @messages = Message.where(read: nil)
    @conversations = Conversation.involving(current_user).order("created_at DESC")
    @conv = Array.new 
    @messages.each do |message| 
      @conv << message.conversation 
    end 
    @conv.uniq!
    respond_to do |format|
      format.js 
    end
  end

  def delete_dialog
    @users = User.where.not("id = ?",current_user.id).order("created_at DESC")
    @conversations = Conversation.involving(current_user).order("created_at DESC")
    respond_to do |format|
      format.js 
    end
  end 


  def show
  	@user = current_user
  end


  def edit
  		@user = current_user
  end


  def update
	  @user = current_user	
      if @user.update!(user_params)
        flash[:notice] = "User updated."
        redirect_to profile_path
      else
        flash[:error] = "Could not update user."
        render :edit
      end
  end

  def add_to_favorites
    user = User.find(params[:user])
    puts user.id
    current_user.favorite << user.id
    redirect_to controller: "users", action: "index"
  end



private
    def user_params
       params.require(:user).permit(:name, :picture, :age, :country, :city )
    end


end

app/helpers/users_helper.rb
module UsersHelper
  def conversation_interlocutor(conversation)
    conversation.recipient == current_user ? conversation.sender : conversation.recipient
  end

  def user_online(users)
  	on_users = users.online_now
  end



end









COUNTRIES = [
  "Afghanistan",
  "Aland Islands",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua And Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegowina",
  "Botswana",
  "Bouvet Island",
  "Brazil",
  "British Indian Ocean Territory",
  "Brunei Darussalam",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cape Verde",
  "Cayman Islands",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Christmas Island",
  "Cocos (Keeling) Islands",
  "Colombia",
  "Comoros",
  "Congo",
  "Congo, the Democratic Republic of the",
  "Cook Islands",
  "Costa Rica",
  "Cote d'Ivoire",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Ethiopia",
  "Falkland Islands (Malvinas)",
  "Faroe Islands",
  "Fiji",
  "Finland",
  "France",
  "French Guiana",
  "French Polynesia",
  "French Southern Territories",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Heard and McDonald Islands",
  "Holy See (Vatican City State)",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran, Islamic Republic of",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea, Democratic People's Republic of",
  "Korea, Republic of",
  "Kuwait",
  "Kyrgyzstan",
  "Lao People's Democratic Republic",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libyan Arab Jamahiriya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macao",
  "Macedonia, The Former Yugoslav Republic Of",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Mexico",
  "Micronesia, Federated States of",
  "Moldova, Republic of",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "Netherlands Antilles",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "Norfolk Island",
  "Northern Mariana Islands",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestinian Territory, Occupied",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Pitcairn",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Reunion",
  "Romania",
  "Russian Federation",
  "Rwanda",
  "Saint Barthelemy",
  "Saint Helena",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Pierre and Miquelon",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Georgia and the South Sandwich Islands",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Svalbard and Jan Mayen",
  "Swaziland",
  "Sweden",
  "Switzerland",
  "Syrian Arab Republic",
  "Taiwan, Province of China",
  "Tajikistan",
  "Tanzania, United Republic of",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks and Caicos Islands",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "United States Minor Outlying Islands",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela",
  "Viet Nam",
  "Virgin Islands, British",
  "Virgin Islands, U.S.",
  "Wallis and Futuna",
  "Western Sahara",
  "Yemen",
  "Zambia",
  "Zimbabwe"
]

app/views/users/_delete.html.erb
            <h3>Delete Dialogs</h3>
            <div style="margin: 0;" class="container">
              <div style="height: 100%; overflow-y: auto;">
              <div class="panel panel-default">
                <table class="table">
                    <tbody>
                      <% @conversations.each do |conversation| %>
                      <% user = User.where(id: conversation.sender_id) %>
                      <tr>
                        <td><%= image_tag(user.first.picture.mini.url, class: "media-object pull-left") %></td>
                        <td><%= link_to conversation_interlocutor(conversation).name, conversation_path(conversation), class: "conversation", "data-cid" => conversation.id  %></td>
                        <td>
                          <%= conversation.messages.last.nil? ? "No messages" : truncate(conversation.messages.last.body, length: 45) %>
                        </td>
                        <td><%= button_to "", {controller: "conversations", action: "destroy",  conversation_id: conversation.id, method: :delete } , {remote: true, :id => "button_trash", :class => "btn-link"}%></td>
                      </tr>
                    </tbody>
                  <% end %>
                  </table>
                  </div>
              </div>
            </div>

app/views/users/_inbox.html.erb
            <h3>All Dialogs</h3>
            <div style="margin: 0;" class="container">
              <div style="height: 100%; overflow-y: auto;">
              <div class="panel panel-default">
                <table class="table">
                    <tbody>
                      <% @conversations.each do |conversation| %>
                      <% user = User.where(id: conversation.sender_id) %>
                      <tr>
                        <td><%= image_tag(user.first.picture.mini.url, class: "media-object pull-left") %></td>
                        <td><%= link_to conversation_interlocutor(conversation).name, conversation_path(conversation), class: "start-conversation", "data-cid" => conversation.id  %></td>
                        <td>
                          <%= conversation.messages.last.nil? ? "No messages" : truncate(conversation.messages.last.body, length: 10) %>
                        </td>
                      </tr>
                    </tbody>
                  <% end %>
                  </table>
                </div>  
              </div>
            </div>

app/views/users/_unread.html.erb
            <h3>Unread</h3>
            <div style="margin: 0;" class="container">
              <div style="height: 100%; overflow-y: on;">
              <div class="panel panel-default">
                <table class="table">
                    <tbody>
                    <% @conv.each do |conversation| %>
                      <% user = User.where(id: conversation.sender_id) %>
                      <tr>
                        <td><%= image_tag(user.first.picture.mini.url, class: "media-object pull-left") %></td>
                        <td><%= link_to conversation_interlocutor(conversation).name, conversation_path(conversation), class: "conversation", "data-cid" => conversation.id  %></td>
                        <td>
                          <%= conversation.messages.last.nil? ? "No messages" : truncate(conversation.messages.last.body, length: 45) %>
                        </td>
                      </tr>
              
                    </tbody> 
                  <% end %>
                  </table>
                </div>
              </div>
            </div>

app/views/users/delete_dialog.js.erb
$("#inbox").html("<%= escape_javascript(render(:partial => 'delete')) %>");

app/views/users/dynamic_show.js.erb
$("#inbox").append("<%= escape_javascript(render (:partial => 'inbox'))) %>");

app/views/users/edit.html.erb
<%= form_for @user, html: { multipart: true } do |f| %>

 
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/index.html.erb
<div class="container">  

 <!-- Left screen -->

  <div class="main col-md-3 col-lg-3 col-sm-3" >
    <div class="left ava row">
        <div id="ava_user"><%= image_tag @user.picture.thumb.url %></br>
          <div id="name"><%= @user.name %></div>
        </div>
       
    </div>
    <div class="left profile row">
      <div class="container">
        <div style="height: 100%;" class="main col-md-3">
          <table class="table">
            <tbody>
              <tr><%= button_to "", {controller: "users", action: "list_conversations"}, {remote: true, :id => "button_inbox"} %></tr>
              <tr><%= button_to "", {controller: "users", action: "unread"}, {remote: true, :id => "button_inbox"} %></tr>
              <tr><%= button_to "", {controller: "users", action: "delete_dialog"}, {remote: true, :id => "button_inbox"} %></tr>
              </tr>
            </tbody>
          </table>
        </div>
        <div style="height: 100%;" class="main col-md-8">
          <div id="inbox" class="inbox"></div>
        </div>
      </div>
    </div>
    <div class="left settings row">
      <div class="container">
        <div style="height: 100%;" class="main col-md-3">
        </div>
        <div style="height: 100%;" class="main col-md-8">
          <div class="inbox"><%= link_to "Settings", profile_path %></div>
          <div class="inbox"> <%= link_to "Go out!", destroy_user_session_path, method: :delete    %></div>
        </div>
      </div>
    </div>
  </div>

 <!-- Middle screen -->

  <div class="main col-md-6">
    <div class="chats container">
      <div id="chaty1" class="main col-md-6"></div>
      <div id="chaty2" class="main col-md-6"></div>
    </div>
  </div>

 <!-- Rigth screen -->
  <div class="main col-md-3 cl-lg-3 col-sm-3">
    <div class="friends row">
      
      <div class="container">

        <div style="height: 100%; overflow-y: auto;">
          <div class="panel panel-default">
            <!-- Default panel contents -->
            <div style="text-align: center;" class="panel-heading">Friends</div>
            <table class="table">
              <tbody>
                <% @favorites.each do |favorite| %>
                  <% friend = User.find(favorite.second_id) %>
                  <tr>
                    <td><%= friend.name %></td>
                    <td>
                      <%= link_to "Send Message", "#", class: "btn btn-success btn-xs start-conversation",
                                "data-sid" => current_user.id, "data-rip" => friend.id %>
                    </td>
                  <%= form_tag(controller: "favorites", action: "delete") do %>
                  <td><%= link_to "Del", {:controller => "favorites", :action => "delete", :user => friend.id, :current_user => current_user.id }%></td>
                    <td><%= image_tag friend.picture.mini.url %></td>

                  </tr>
                <% end %>

                <% end %>

            </tbody>
          </table>
        </div>

        </div>

    </div>
  </div>
    <div class="online row">
  
      <div class="container">

  <div style="height: 100%; overflow-y: auto;">
        <div class="panel panel-default">
          <!-- Default panel contents -->
          <div style="text-align: center;" class="panel-heading">Online</div>

          <table class="table">
          <% index = 0 %>
            <tbody>
            <% if user_online(@users) == [] %>
              <tr>
              <td></td>
              <td>No users online.</td>
              </tr>
            <% else%>
            <% user_online(@users).each do |user| %>
                <tr>
                  <td><%= index +=1 %></td>
                  <td><%= user.name %></td>
                  <td>
                    <%= link_to "Send Message", "#", class: "btn btn-success btn-xs start-conversation",
                                "data-sid" => current_user.id, "data-rip" => user.id %>
                  </td>
                  <td><%= image_tag user.picture.mini.url %></td>
                </tr>
            <% end %>
            <% end %> 

            </tbody>
          </table>
        </div>

        </div>

    </div>
  </div>
    <div class="all row">
      <div class="container">

        <div style="height: 100%; overflow-y: auto;">
          <div class="panel panel-default">
            <!-- Default panel contents -->
            <div style="text-align: center;" class="panel-heading">All Users</div>
            <table class="table">
              <tbody>
              <% @users.each_with_index do |user, index| %>
                <tr>
                  <td><%= index +=1 %></td>
                  <td><%= user.name %></td>
                  <td>
                    <%= link_to "Send Message", "#", class: "btn btn-success btn-xs start-conversation",
                                "data-sid" => current_user.id, "data-rip" => user.id %>
                  </td>
                  <%= form_tag(controller: "favorites", action: "add") do %>
                  <td><%= link_to "Add", {:controller => "favorites", :action => "add", :user => user.id, :current_user => current_user.id }%></td>
                  <% end %>
                  <td><%= image_tag user.picture.mini.url %></td>
                </tr>
            <% end %>

            </tbody>
          </table>
        </div>

      </div>
    </div>
  </div>
</div>

          <!-- Table -
    <div style="height: 300px; overflow-y: auto;">
      <div class="panel panel-default">
        <!-- Default panel contents --
        <div class="panel-heading">Registered Users</div>


        <table class="table">
          <thead>
          <tr>
            <th>#</th>
            <th>Name</th>
            <th></th>
          </tr>
          </thead>
          <tbody>
          <% @users.each_with_index do |user, index| %>
              <tr>
                <td><%= index +=1 %></td>
                <td><%= user.name %></td>
                
                <td>
                  <%= link_to "Send Message", "#", class: "btn btn-success btn-xs start-conversation",
                              "data-sid" => current_user.id, "data-rip" => user.id %>
                </td>
                <td><%= image_tag user.picture.thumb.url %></td>
              </tr>
          <% end %>

          </tbody>
        </table>
      </div>

    </div>
    <hr>
    <h3>Your Conversations</h3>

    <div style="height: 400px; overflow-y: auto;">
      <% if @conversations.any? %>
          <ul class="media-list">
              <% @conversations.each do |conversation| %>
                <li class="media">
                <% user = User.where(id: conversation.sender_id) %>
                  <%= image_tag(user.first.picture.thumb.url, class: "media-object pull-left")  %>
                  <div class="media-body">
                         <h4 class="media-heading"><%= link_to conversation_interlocutor(conversation).name, conversation_path(conversation), class: "conversation", "data-cid" => conversation.id  %></h4>
                        <p><%= conversation.messages.last.nil? ? "No messages" : truncate(conversation.messages.last.body, length: 45) %></p>
                  </div>
                </li>
            <% end %>
          </ul>
      <% else %>
          <p>You have no conversations. Click send message with any user to create one.</p>
      <% end %>
    </div>

  </div>

  <div class="col-md-4">

  </div>

</div>

app/views/users/list_conversations.js.erb
$("#inbox").html("<%= escape_javascript(render(:partial => 'inbox')) %>");

app/views/users/show.erb
<p id="notice"><%= notice %></p>
<div class="container"> 
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>
 
 
<p>
  <strong>Avatar:</strong>
  <%= image_tag @user.picture.thumb.url %>
</p>


 
<%= link_to 'Edit', profile_edit_path(@user) %> |
<%= link_to 'Back', root_path %>

</div>

app/views/users/unread.js.erb
$("#inbox").html("<%= escape_javascript(render(:partial => 'unread')) %>");