config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users

  resources :users
  match '/profile_update',  to: 'users#update',            via: 'get'
  match '/profile_edit',  to: 'users#edit',            via: 'get'
  match '/profile',  to: 'users#show',            via: 'get'
  match '/inbox', to: 'users#list_conversations',       via: 'post' ,    defaults:{ format: 'js' }
  match '/unread', to: 'users#unread',       via: 'post' ,    defaults:{ format: 'js' }
  match '/delete', to: 'users#delete_dialog',       via: 'post' ,    defaults:{ format: 'js' }
  match '/delete_selected', to: 'conversations#destroy',       via: 'post' ,    defaults:{ format: 'js' }
  match '/favarite', to: 'favorites#add',       via: 'get'
  match '/del_from_favarite', to: 'favorites#delete',       via: 'get' 
  authenticated :user do
    root 'users#index'
  end

  unauthenticated :user do
    devise_scope :user do
      get "/" => "devise/sessions#new"
    end
  end

  resources :conversations do
    resources :messages
  end

  

end

app/views/layouts/_nav.html.erb
<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="nav-container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Chatyfy</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Chatyfy", root_path, class: "navbar-brand" %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav pull-right">
        <% if user_signed_in? %>
            <li>
              <%= link_to "Hi, #{current_user.name}" %>
            </li>
            <li>
              <%= link_to "Logout", destroy_user_session_path, method: :delete	  %>
            </li>
            <li>
              <%= link_to "Profile", profile_path %>
            </li>
        <% else %>
            <li>
              <%= link_to "Signin", new_user_session_path %>
            </li>
            <li>
              <%= link_to "Signup", new_user_registration_path %>
            </li>
        <% end %>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <meta content='<%= user_signed_in? ? current_user.id : "" %>' name='user-id'/>

  <title>Chat for Zombies</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  
  <%= stylesheet_link_tag '//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!-- shiv here -->

</head>

<body>
<div>
  <!-- flash messages here -->
  <%= yield %>

</div>

</body>

</html>